import os

# مسار الملف الناتج اللي راح تسحبه أو تقراه أداة الربط بروبلوكس ستوديو
OUTPUT_DIR = "output"
OUTPUT_FILE = os.path.join(OUTPUT_DIR, "generated_script.lua")

def parse_idea_to_luau(idea: str) -> str:
    """
    منطقة تحليل الأفكار (يقدر يتطور المنطق هنا أو تضيف قواعد أكثر)
    """
    idea_lower = idea.lower()
    
    # مثال 1: لو الأمر يتعلق ببناء جزء أو بارت
    if "ابني" in idea or "سوي بارت" in idea or "part" in idea_lower:
        return """
-- Generated by Local Generator
local part = Instance.new("Part")
part.Size = Vector3.new(4, 1, 4)
part.Position = Vector3.new(0, 5, 0)
part.Anchored = true
part.BrickColor = BrickColor.new("Bright red")
part.Parent = workspace
print("تم بناء البارت بنجاح!")
"""
    
    # مثال 2: لو الأمر يتعلق بطباعة رسالة أو ترحيب
    elif "اطبع" in idea or "رسالة" in idea or "print" in idea_lower:
        return """
-- Generated by Local Generator
print("أهلاً بك في لعبة روبلوكس - تم التحديث بواسطة الجينيريتور المحلي!")
"""
    
    # الافتراضي لو ما فهم القاعدة
    else:
        return f"""
-- Generated for idea: {idea}
-- [ملاحظة]: لم يتم التعرف على قاعدة مخصصة لهذه الفكرة، تمت إضافة قالب افتراضي.
print("الفكرة الواردة: {idea}")
"""

def save_to_file(content: str):
    if not os.path.exists(OUTPUT_DIR):
        os.makedirs(OUTPUT_DIR)
        
    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write(content.strip())
    print(f"[نجاح] تم تحديث الملف بنجاح في: {OUTPUT_FILE}")

def main():
    print("=== نظام توليد أكواد روبلوكس المحلي ===")
    while True:
        idea = input("\nاكتب الفكرة أو التعديل (أو اكتب 'خروج' للإنهاء): ")
        if idea.strip().lower() in ["خروج", "exit", "quit"]:
            print("إغلاق البرنامج.")
            break
            
        if not idea.strip():
            print("الرجاء إدخال فكرة صحيحة.")
            continue
            
        luau_code = parse_idea_to_luau(idea)
        save_to_file(luau_code)

if __name__ == "__main__":
    main()
